//! Emits EIP-2537 encoded BLS12-381 test vectors for the Solidity pairing
//! harness in `contracts/test/auctionkit/BlsPairing.t.sol`.
//!
//! Run: `cargo run -p bte-crypto --example eip2537_vectors`
//!
//! Exists because arkworks' own serialization is not EIP-2537's. The precompile
//! wants each Fp as 48 big-endian bytes left-padded to 64, points uncompressed
//! and never compressed, which is a conversion worth doing once in code rather
//! than by hand into a hex literal nobody can check.

use ark_bls12_381::{Fq, Fq2, G1Affine, G2Affine};
use ark_ec::AffineRepr;
use ark_ff::{BigInteger, PrimeField};

/// One Fp: 48 big-endian bytes, left-padded into a 64-byte word.
fn fp(x: &Fq) -> Vec<u8> {
    let be = x.into_bigint().to_bytes_be(); // 48 bytes
    let mut out = vec![0u8; 64 - be.len()];
    out.extend_from_slice(&be);
    out
}

/// G1: x || y, 128 bytes.
fn g1(p: &G1Affine) -> Vec<u8> {
    if p.is_zero() {
        return vec![0u8; 128];
    }
    let mut out = fp(&p.x().unwrap());
    out.extend(fp(&p.y().unwrap()));
    out
}

/// G2: x.c0 || x.c1 || y.c0 || y.c1, 256 bytes.
///
/// Note the c0-before-c1 ordering: EIP-2537 fixes it, and swapping it produces
/// a point that decodes without error and pairs to the wrong value.
fn g2(p: &G2Affine) -> Vec<u8> {
    if p.is_zero() {
        return vec![0u8; 256];
    }
    let x: Fq2 = p.x().unwrap();
    let y: Fq2 = p.y().unwrap();
    let mut out = fp(&x.c0);
    out.extend(fp(&x.c1));
    out.extend(fp(&y.c0));
    out.extend(fp(&y.c1));
    out
}

fn main() {
    let p = G1Affine::generator();
    let q = G2Affine::generator();
    let neg_p = -p;

    // e(P, Q) * e(-P, Q) == 1 by bilinearity. Two real terms, so it exercises
    // point decoding and subgroup checks rather than the infinity short-circuit.
    let mut holds = g1(&p);
    holds.extend(g2(&q));
    holds.extend(g1(&neg_p));
    holds.extend(g2(&q));

    // e(P, Q) alone is not 1 — P and Q are generators, so the pairing is a
    // primitive root. This is the negative control: without it, a harness that
    // always returned true would pass every other test here.
    let mut does_not_hold = g1(&p);
    does_not_hold.extend(g2(&q));

    println!("// generated by `cargo run -p bte-crypto --example eip2537_vectors`");
    println!(
        "// e(P,Q) * e(-P,Q) == 1   ({} bytes, 2 terms)",
        holds.len()
    );
    println!("hex\"{}\"", hex::encode(&holds));
    println!();
    println!("// e(P,Q) != 1   ({} bytes, 1 term)", does_not_hold.len());
    println!("hex\"{}\"", hex::encode(&does_not_hold));
}
