//! An operator's side of a DKG round, driven over the coordinator's relay.
//!
//! One `RoundDriver` per round. Every `step` reads the relay's new
//! envelopes since the last one it saw, feeds dealings to the player (and
//! acknowledges them), feeds acknowledgements to the dealer, closes the
//! dealer's log once every player acknowledged or the round's deadline
//! passed, and finalizes the share once the coordinator has settled the
//! round with a published set of logs. The whole state is rebuilt from the
//! relay after a restart: the dealer's dealing is derived from the identity
//! and the round digest, so it is regenerated byte for byte, and every
//! message ever posted is still on the relay.

use crate::identity::OperatorIdentity;
use anyhow::{anyhow, bail, Context, Result};
use base64::Engine;
use bte_crypto::tbte::dkg::{
    box_aad, identity_key_bytes, identity_key_from_bytes, open_box, seal_box, Envelope,
    IdentityKey, Kind, OperatorRound, RoundConfig, RoundResult,
};
use hkdf::Hkdf;
use serde::Deserialize;
use sha2::Sha256;
use std::collections::{HashMap, HashSet};

const B64: base64::engine::GeneralPurpose = base64::engine::general_purpose::STANDARD;

#[derive(Clone, Debug, Deserialize)]
pub struct OperatorEntry {
    pub identity: String,
    #[serde(rename = "box")]
    pub box_key: String,
}

/// A round as the relay describes it.
#[derive(Clone, Debug, Deserialize)]
pub struct RoundInfo {
    pub id: String,
    pub committee_tag: String,
    pub round: u64,
    pub operators: Vec<OperatorEntry>,
    pub digest: String,
    pub status: String,
    pub ack_deadline: i64,
    #[serde(default)]
    pub committee_id: Option<String>,
    #[serde(default)]
    pub logs: Option<Vec<i64>>,
}

impl RoundInfo {
    pub fn config(&self) -> Result<RoundConfig> {
        let mut operators = Vec::with_capacity(self.operators.len());
        for o in &self.operators {
            let raw = hex::decode(&o.identity).context("operator identity hex")?;
            operators.push(identity_key_from_bytes(&raw).map_err(|e| anyhow!("{e}"))?);
        }
        let config = RoundConfig {
            committee_tag: self.committee_tag.as_bytes().to_vec(),
            round: self.round,
            operators,
        };
        if hex::encode(config.digest()) != self.digest.to_lowercase() {
            bail!("relay's round digest does not match its configuration");
        }
        Ok(config)
    }

    fn box_key_of(&self, identity_hex: &str) -> Option<[u8; 32]> {
        let entry = self
            .operators
            .iter()
            .find(|o| o.identity.eq_ignore_ascii_case(identity_hex))?;
        let raw = hex::decode(&entry.box_key).ok()?;
        raw.try_into().ok()
    }
}

#[derive(Deserialize)]
struct EnvelopeRow {
    seq: i64,
    envelope_b64: String,
}

/// HTTP access to the relay.
pub struct Relay {
    pub client: reqwest::Client,
    pub base: String,
}

impl Relay {
    pub fn new(base: impl Into<String>) -> Relay {
        Relay {
            client: reqwest::Client::new(),
            base: base.into(),
        }
    }

    pub async fn rounds_for(&self, identity_hex: &str) -> Result<Vec<RoundInfo>> {
        #[derive(Deserialize)]
        struct Rounds {
            rounds: Vec<RoundInfo>,
        }
        let r: Rounds = self
            .client
            .get(format!("{}/v0/dkg/pending", self.base))
            .query(&[("identity", identity_hex)])
            .send()
            .await?
            .error_for_status()?
            .json()
            .await?;
        Ok(r.rounds)
    }

    pub async fn round(&self, id: &str) -> Result<RoundInfo> {
        Ok(self
            .client
            .get(format!("{}/v0/dkg/rounds/{id}", self.base))
            .send()
            .await?
            .error_for_status()?
            .json()
            .await?)
    }

    pub async fn envelopes(&self, id: &str, since: i64) -> Result<Vec<(i64, Envelope)>> {
        #[derive(Deserialize)]
        struct Rows {
            envelopes: Vec<EnvelopeRow>,
        }
        let rows: Rows = self
            .client
            .get(format!("{}/v0/dkg/rounds/{id}/envelopes", self.base))
            .query(&[("since", since)])
            .send()
            .await?
            .error_for_status()?
            .json()
            .await?;
        let mut out = Vec::with_capacity(rows.envelopes.len());
        for row in rows.envelopes {
            let bytes = B64.decode(&row.envelope_b64).context("envelope base64")?;
            out.push((
                row.seq,
                Envelope::from_bytes(&bytes).map_err(|e| anyhow!("{e}"))?,
            ));
        }
        Ok(out)
    }

    pub async fn post(&self, id: &str, envelope: &Envelope) -> Result<bool> {
        let resp: serde_json::Value = self
            .client
            .post(format!("{}/v0/dkg/rounds/{id}/envelopes", self.base))
            .json(&serde_json::json!({"envelope_b64": B64.encode(envelope.to_bytes())}))
            .send()
            .await?
            .error_for_status()?
            .json()
            .await?;
        Ok(resp["accepted"].as_bool().unwrap_or(false))
    }
}

/// What one step achieved.
#[derive(Debug, PartialEq, Eq)]
pub enum Progress {
    /// Still exchanging messages.
    Working,
    /// Our dealer log is posted; waiting for the relay to settle the round.
    LogPosted,
    /// The share is ours. Save it.
    Done,
    /// The relay marked the round failed.
    Failed(String),
}

pub struct RoundDriver {
    info: RoundInfo,
    config: RoundConfig,
    me_key: IdentityKey,
    round: Option<OperatorRound>,
    /// Highest envelope seq consumed.
    since: i64,
    /// Envelopes seen, kept so a private dealing can wait for its public half.
    publics: HashMap<String, Vec<u8>>,
    pending_private: HashMap<String, Vec<u8>>,
    acked_dealers: HashSet<String>,
    acks_received: HashSet<String>,
    posted_own: bool,
    dealer_closed: bool,
    /// Log envelopes by seq, for finalization with the relay's chosen set.
    logs: HashMap<i64, Vec<u8>>,
    pub result: Option<RoundResult>,
}

/// The dealer's seed: a function of the identity and the round, so a
/// restarted process deals the same polynomial again.
fn dealer_seed(me: &OperatorIdentity, digest: &[u8; 32]) -> [u8; 32] {
    let ikm = bte_crypto::tbte::dkg::identity_bytes(&me.identity);
    let hk = Hkdf::<Sha256>::new(Some(b"PEAL-BTE-V1-DKG-DEALER-SEED"), &ikm);
    let mut seed = [0u8; 32];
    hk.expand(digest, &mut seed).expect("valid length");
    seed
}

impl RoundDriver {
    pub fn new(me: &OperatorIdentity, info: RoundInfo) -> Result<RoundDriver> {
        let config = info.config()?;
        let me_key = me.key();
        let me_hex = me.key_hex();
        if !info
            .operators
            .iter()
            .any(|o| o.identity.eq_ignore_ascii_case(&me_hex))
        {
            bail!("this identity is not an operator of round {}", info.id);
        }
        let round = OperatorRound::start(
            config.clone(),
            me.identity.clone(),
            dealer_seed(me, &config.digest()),
        )
        .map_err(|e| anyhow!("{e}"))?;
        Ok(RoundDriver {
            info,
            config,
            me_key,
            round: Some(round),
            since: 0,
            publics: HashMap::new(),
            pending_private: HashMap::new(),
            acked_dealers: HashSet::new(),
            acks_received: HashSet::new(),
            posted_own: false,
            dealer_closed: false,
            logs: HashMap::new(),
            result: None,
        })
    }

    pub fn round_id(&self) -> &str {
        &self.info.id
    }

    pub fn config(&self) -> &RoundConfig {
        &self.config
    }

    fn sign(
        &self,
        me: &OperatorIdentity,
        kind: Kind,
        to: Option<IdentityKey>,
        payload: Vec<u8>,
    ) -> Envelope {
        Envelope::sign(&me.identity, self.config.digest(), kind, to, payload)
    }

    /// One poll of the relay.
    pub async fn step(
        &mut self,
        me: &OperatorIdentity,
        relay: &Relay,
        now: i64,
    ) -> Result<Progress> {
        if self.result.is_some() {
            return Ok(Progress::Done);
        }
        let digest = self.config.digest();
        let latest = relay.round(&self.info.id).await?;
        if latest.status == "failed" {
            return Ok(Progress::Failed(format!("round {} failed", self.info.id)));
        }
        // A settled round takes no more envelopes; a restarted node only
        // replays what is there to rebuild its player and finalize.
        let can_post = latest.status == "open";

        // Our own dealing, once per process (the relay dedupes).
        if can_post && !self.posted_own {
            let round = self.round.as_ref().context("round already finalized")?;
            relay
                .post(
                    &self.info.id,
                    &self.sign(me, Kind::DealerPublic, None, round.public_message()),
                )
                .await?;
            let mut rng = bte_crypto::os_rng();
            for (player, plain) in round.private_messages() {
                let player_hex = hex::encode(identity_key_bytes(&player));
                let recipient_box = self
                    .info
                    .box_key_of(&player_hex)
                    .with_context(|| format!("no box key for operator {player_hex}"))?;
                let sealed = seal_box(
                    &recipient_box,
                    &box_aad(&digest, &self.me_key, &recipient_box),
                    &plain,
                    &mut rng,
                );
                relay
                    .post(
                        &self.info.id,
                        &self.sign(me, Kind::DealerPrivate, Some(player), sealed),
                    )
                    .await?;
            }
            self.posted_own = true;
        }

        // Everything new on the relay.
        let new = relay.envelopes(&self.info.id, self.since).await?;
        for (seq, envelope) in new {
            self.since = self.since.max(seq);
            if !envelope.verify(&self.config) {
                continue;
            }
            let from_hex = hex::encode(identity_key_bytes(&envelope.from));
            let to_me = envelope.to.as_ref() == Some(&self.me_key);
            match envelope.kind {
                Kind::DealerPublic => {
                    self.publics
                        .entry(from_hex.clone())
                        .or_insert(envelope.payload);
                }
                Kind::DealerPrivate if to_me => {
                    self.pending_private
                        .entry(from_hex.clone())
                        .or_insert(envelope.payload);
                }
                Kind::Ack if to_me => {
                    if let Some(round) = self.round.as_mut() {
                        match round.receive_ack(&envelope.from, &envelope.payload) {
                            Ok(()) => {
                                self.acks_received.insert(from_hex);
                            }
                            Err(e) => tracing::warn!(from = from_hex, error = %e, "ack rejected"),
                        }
                    }
                }
                Kind::Log => {
                    self.logs.insert(seq, envelope.payload);
                }
                _ => {}
            }
        }

        // Acknowledge every dealing whose public half we have.
        let ready: Vec<String> = self
            .pending_private
            .keys()
            .filter(|d| self.publics.contains_key(*d) && !self.acked_dealers.contains(*d))
            .cloned()
            .collect();
        for dealer_hex in ready {
            let dealer =
                identity_key_from_bytes(&hex::decode(&dealer_hex)?).map_err(|e| anyhow!("{e}"))?;
            let my_box = me.box_secret.public();
            let sealed = &self.pending_private[&dealer_hex];
            let plain = match open_box(&me.box_secret, &box_aad(&digest, &dealer, &my_box), sealed)
            {
                Ok(p) => p,
                Err(e) => {
                    tracing::warn!(dealer = dealer_hex, error = %e, "private dealing did not open");
                    self.acked_dealers.insert(dealer_hex);
                    continue;
                }
            };
            let round = self.round.as_mut().context("round already finalized")?;
            match round.receive_dealing(&dealer, &self.publics[&dealer_hex], &plain) {
                Ok(Some(ack)) if can_post => {
                    relay
                        .post(&self.info.id, &self.sign(me, Kind::Ack, Some(dealer), ack))
                        .await?;
                }
                Ok(Some(_)) => {}
                Ok(None) => {}
                Err(e) => tracing::warn!(dealer = dealer_hex, error = %e, "dealing rejected"),
            }
            self.acked_dealers.insert(dealer_hex);
        }

        // Close our dealer log once everyone acknowledged or time is up.
        let everyone = self.acks_received.len() >= self.config.n() as usize;
        if can_post && !self.dealer_closed && (everyone || now >= self.info.ack_deadline) {
            if let Some(round) = self.round.as_mut() {
                let log = round.finalize_dealer().map_err(|e| anyhow!("{e}"))?;
                relay
                    .post(&self.info.id, &self.sign(me, Kind::Log, None, log))
                    .await?;
            }
            self.dealer_closed = true;
        }

        // Finalize with the relay's settled log set.
        match latest.status.as_str() {
            "complete" => {
                let seqs = latest.logs.clone().context("complete round without logs")?;
                let mut chosen = Vec::with_capacity(seqs.len());
                for seq in &seqs {
                    match self.logs.get(seq) {
                        Some(log) => chosen.push(log.clone()),
                        None => return Ok(Progress::LogPosted),
                    }
                }
                let round = self.round.take().context("round already finalized")?;
                let mut seed = [0u8; 32];
                bte_crypto::rand::RngCore::fill_bytes(&mut bte_crypto::os_rng(), &mut seed);
                let result = round.finalize(&chosen, seed).map_err(|e| anyhow!("{e}"))?;
                let expected = latest.committee_id.clone().unwrap_or_default();
                if hex::encode(result.params.digest()) != expected {
                    bail!("our finalize disagrees with the relay's committee id");
                }
                self.info = latest;
                self.result = Some(result);
                Ok(Progress::Done)
            }
            "failed" => Ok(Progress::Failed(format!("round {} failed", self.info.id))),
            _ if self.dealer_closed => Ok(Progress::LogPosted),
            _ => Ok(Progress::Working),
        }
    }
}
