/** Extract the ABIs the client needs from forge artifacts.
 *
 * Generated rather than hand-written: a hand-copied ABI drifts from the
 * contract silently, and the first symptom is a decode failure at runtime
 * against a chain, which is the worst place to find out.
 *
 * Run: `node scripts/abis.mjs` from packages/auctionkit.
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const out = join(here, '..', '..', '..', 'contracts', 'out');

const WANTED = {
  SealedBidAuction: 'SealedBidAuction.sol/SealedBidAuction.json',
  CommitteeRegistry: 'CommitteeRegistry.sol/CommitteeRegistry.json',
  DemoToken: 'DemoToken.sol/DemoToken.json',
  DemoFaucet: 'DemoFaucet.sol/DemoFaucet.json',
  AuctionFactory: 'AuctionFactory.sol/AuctionFactory.json',
};

let ts = `// GENERATED by scripts/abis.mjs — do not edit.\n// Source: contracts/out/*, produced by \`forge build\`.\n\n`;
for (const [name, path] of Object.entries(WANTED)) {
  const artifact = JSON.parse(readFileSync(join(out, path), 'utf8'));
  ts += `export const ${name}Abi = ${JSON.stringify(artifact.abi)} as const;\n\n`;
}

mkdirSync(join(here, '..', 'src'), { recursive: true });
writeFileSync(join(here, '..', 'src', 'abi.ts'), ts);
console.log(`wrote src/abi.ts (${Object.keys(WANTED).length} ABIs)`);
